### ISSUE TITLE
Build fails on kernel 5.11.14_1 (void linux)

### ISSUE THREAD

**Issue by gronka** [maaarghk/soundwire-dkms#5]
Void linux kernel 5.11.14_1
pulseaudio 14.2
sof-firmware-1.7_1

lol - this is odd:
supper@localhost ~ $ dkms --version
dkms:[INSERT_VERSION_HERE]

soundwire-dkms on branch latest-sofproject
i copied v1.4.0 from a comment online, but this is in dms.conf:
PACKAGE_NAME="soundwire"
PACKAGE_VERSION="1.3.1"

Bottom of make.log:
```
  LD [M]  /var/lib/dkms/soundwire/1.4.0/build/soc/codecs/snd-soc-wm8904.o
  LD [M]  /var/lib/dkms/soundwire/1.4.0/build/soc/codecs/snd-soc-wm8903.o
  LD [M]  /var/lib/dkms/soundwire/1.4.0/build/soc/codecs/snd-soc-wm8962.o
  MODPOST /var/lib/dkms/soundwire/1.4.0/build/Module.symvers
ERROR: modpost: "sst_hsw_device_set_config" [/var/lib/dkms/soundwire/1.4.0/build/soc/intel/boards/snd-soc-sst-haswell.ko] undefined!
make[2]: *** [scripts/Makefile.modpost:111: /var/lib/dkms/soundwire/1.4.0/build/Module.symvers] Error 1
make[2]: *** Deleting file '/var/lib/dkms/soundwire/1.4.0/build/Module.symvers'
make[1]: *** [Makefile:1724: modules] Error 2
make[1]: Leaving directory '/usr/src/kernel-headers-5.11.14_1'
make: *** [Makefile:10: all] Error 2
```

Edit: I'm seeing comments online now that this package is no longer needed with my current software. But I still only see "Dummy Output" in pavucontrol. Is there a way I can validate?

**Comment by maaarghk** [comment]
You don't need this on Kernel 5.11, just enable the relevant config options when building the kernel, or ask your distro maintainer to do that.
